<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-19 06:13
=======
# Generated by Django 5.0.6 on 2024-05-20 11:04
>>>>>>> 7b4a247334409ecc4f201fd6c81ff925389d25b6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=100)),
=======
                ('title', models.CharField(max_length=50)),
>>>>>>> 7b4a247334409ecc4f201fd6c81ff925389d25b6
                ('content', models.TextField()),
            ],
        ),
    ]
